apiVersion: apps/v1
kind: Deployment
metadata:
  name: clojure-k8s-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: clojure-k8s-demo
  template:
    metadata:
      labels:
        app: clojure-k8s-demo
    spec:
      containers:
      - name: clojure-k8s-demo
        image: clojure-k8s-demo:v1
        ports:
        - containerPort: 3000
