apiVersion: v1
kind: Service
metadata:
  name: clojure-k8s-demo-service
spec:
  selector:
    app: clojure-k8s-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
